### ISSUE TITLE
"..." does not show up on collapsed items

### ISSUE THREAD

**Issue by Lunatrius** [bhollis/jsonview#89]
It doesn't show up on default, 100% zoom. Pressing `CTRL+PLUS` (at least) once will show the triple dot just fine.
I've tried tweaking the height of `.collapsible.collapsed` a bit and 0.9em shows the dots all the time, but that changes the height of those lines slightly.

Edit: the following works pretty well:
```css
.collapsible.collapsed:before {
    font-size: 0.9em;
    vertical-align: text-top;
}
```
